version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "deps"
    groups:
      cargo-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "ci"
    groups:
      github-actions:
        patterns:
          - "*"
