[graph]
targets = []
all-features = true

[advisories]
version = 2
yanked = "warn"

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "ISC",
    "BSD-3-Clause",
    "MPL-2.0",
    "CDLA-Permissive-2.0",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
