name: Change request
description: A change to this repository
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: want
    attributes:
      label: What should change
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why
    validations:
      required: true
